language: java
jdk:
  - oraclejdk8
install: true
script: mvn -fae -U -B clean install -P check
env:
  global:
    - secure: "IEyFpcRUmY/SU3rIHbGRvhK+UmWjGe24CBCFdjMp+YN7oFX5QJ0mdRsXCFucDHcwPvUPqhW2wTfXYmahR98hKfCDKSMNTn3Yuw5ny2Q/3erZJKlb7A1GeVKnsG0MJ11tEDn+qL8ueghcTo/kIPUWD2H16wUotxq7UhwiNMuIim0="
after_success: chmod +x .travis/on_success.sh && .travis/on_success.sh
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_failure: always
