language: java
jdk:
- oraclejdk8
script: mvn -fae -U -B clean install -P check
after_success: 
- chmod +x .travis/deploy-docs.sh && .travis/deploy-docs.sh
- curl -Ls https://git.io/deploy-maven-snapshot | bash
# start dependend builds
- SCRIPT=$(mktemp)
- curl -Ls https://git.io/trigger-build -o "$SCRIPT"
- bash "${SCRIPT}" 52North/dao-series-api develop
- bash "${SCRIPT}" 52North/dao-series-api "version/v3.x"
- bash "${SCRIPT}" 52North/ckan-data-harvester
env:
  global:
  - SNAPSHOT_BRANCH: "develop"
cache:
  directories
  - $HOME/.m2
notifications:
  irc:
    channels:
    - "chat.freenode.net#52north"
    on_failure: always
